### PR TITLE
Do not start netlink, but make sure it's bundled with the application

### PR DESCRIPTION
**Pull request by sargun**

### CODE REVIEW

**Comment by sargun** [comment]
@spacejam

**Comment by spacejam** [comment]
what's the motivation?

**Comment by sargun** [comment]
When gen_netlink starts up it tries to listen for routing changes, and a couple other things that we're not using. No reason to waste those resources. 

Also, when it breaks, it makes debugging harder.

**Comment by spacejam** [comment]
👍 LGTM

**Pull request merged**
