### PR TITLE
Webmachine has moved to it's own organization

### PR DESCRIPTION
**Pull request by iamthemuffinman**

### CODE REVIEW

**Comment by iamthemuffinman** [comment]
That's interesting. Why is CircleCI running the build for this and not Velocity or Mesosphere's TeamCity?

**Comment by sargun** [comment]
@iamthemuffinman that's a good question. I don't know why velocity didn't pick this up.

**Comment by sargun** [comment]
Can you also upgrade the rebar3 lock file? That should basically require running the command ./rebar3 upgrade we machine and checking in rebar.lock

**Comment by iamthemuffinman** [comment]
@sargun Updated and squashed.

**Pull request merged**
